import { keyBy } from 'lodash'

const QK_LAYER_TAP: number = 0x4000
const QK_ONE_SHOT_MOD: number = 0x5500
const QK_MOD_TAP: number = 0x6000

const MOD_LCTL: number = 0x01
const MOD_LSFT: number = 0x02
const MOD_LALT: number = 0x04
const MOD_LGUI: number = 0x08
const MOD_RCTL: number = 0x11
const MOD_RSFT: number = 0x12
const MOD_RALT: number = 0x14
const MOD_RGUI: number = 0x18

const MOD_HYPR: number = 0xf
const MOD_MEH: number = 0x7

const QK_LCTL: number = 0x0100
const QK_LSFT: number = 0x0200
const QK_LALT: number = 0x0400
const QK_LGUI: number = 0x0800
const QK_RCTL: number = 0x1100
const QK_RSFT: number = 0x1200
const QK_RALT: number = 0x1400
const QK_RGUI: number = 0x1800

const KEY_CODES_BASIC = [
	{ hex: 0x04, code: 'KC_A', label: 'A', macro: ['a'] },
	{ hex: 0x05, code: 'KC_B', label: 'B', macro: ['b'] },
	{ hex: 0x06, code: 'KC_C', label: 'C', macro: ['c'] },
	{ hex: 0x07, code: 'KC_D', label: 'D', macro: ['d'] },
	{ hex: 0x08, code: 'KC_E', label: 'E', macro: ['e'] },
	{ hex: 0x09, code: 'KC_F', label: 'F', macro: ['f'] },
	{ hex: 0x0a, code: 'KC_G', label: 'G', macro: ['g'] },
	{ hex: 0x0b, code: 'KC_H', label: 'H', macro: ['h'] },
	{ hex: 0x0c, code: 'KC_I', label: 'I', macro: ['i'] },
	{ hex: 0x0d, code: 'KC_J', label: 'J', macro: ['j'] },
	{ hex: 0x0e, code: 'KC_K', label: 'K', macro: ['k'] },
	{ hex: 0x0f, code: 'KC_L', label: 'L', macro: ['l'] },
	{ hex: 0x10, code: 'KC_M', label: 'M', macro: ['m'] },
	{ hex: 0x11, code: 'KC_N', label: 'N', macro: ['n'] },
	{ hex: 0x12, code: 'KC_O', label: 'O', macro: ['o'] },
	{ hex: 0x13, code: 'KC_P', label: 'P', macro: ['p'] },
	{ hex: 0x14, code: 'KC_Q', label: 'Q', macro: ['q'] },
	{ hex: 0x15, code: 'KC_R', label: 'R', macro: ['r'] },
	{ hex: 0x16, code: 'KC_S', label: 'S', macro: ['s'] },
	{ hex: 0x17, code: 'KC_T', label: 'T', macro: ['t'] },
	{ hex: 0x18, code: 'KC_U', label: 'U', macro: ['u'] },
	{ hex: 0x19, code: 'KC_V', label: 'V', macro: ['v'] },
	{ hex: 0x1a, code: 'KC_W', label: 'W', macro: ['w'] },
	{ hex: 0x1b, code: 'KC_X', label: 'X', macro: ['x'] },
	{ hex: 0x1c, code: 'KC_Y', label: 'Y', macro: ['y'] },
	{ hex: 0x1d, code: 'KC_Z', label: 'Z', macro: ['z'] },
	{ hex: 0x1e, code: 'KC_1', label: '!\n1', macro: ['1'] },
	{ hex: 0x1f, code: 'KC_2', label: '@\n2', macro: ['2'] },
	{ hex: 0x20, code: 'KC_3', label: '#\n3', macro: ['3'] },
	{ hex: 0x21, code: 'KC_4', label: '$\n4', macro: ['4'] },
	{ hex: 0x22, code: 'KC_5', label: '%\n5', macro: ['5'] },
	{ hex: 0x23, code: 'KC_6', label: '^\n6', macro: ['6'] },
	{ hex: 0x24, code: 'KC_7', label: '&\n7', macro: ['7'] },
	{ hex: 0x25, code: 'KC_8', label: '*\n8', macro: ['8'] },
	{ hex: 0x26, code: 'KC_9', label: '(\n9', macro: ['9'] },
	{ hex: 0x27, code: 'KC_0', label: ')\n0', macro: ['0'] },
	{
		hex: 0x28,
		code: 'KC_ENTER',
		label: 'Enter',
		macro: ['enter'],
		macroCode: ['KC_ENT'],
	},
	{
		hex: 0x29,
		code: 'KC_ESCAPE',
		label: 'Esc',
		macro: ['esc'],
		macroCode: ['KC_ESC'],
	},
	{
		hex: 0x2a,
		code: 'KC_BSPACE',
		label: 'Bksp',
		macro: ['backspace'],
		macroCode: ['KC_BSPC'],
	},
	{ hex: 0x2b, code: 'KC_TAB', label: 'Tab', macro: ['tab'] },
	{
		hex: 0x2c,
		code: 'KC_SPACE',
		label: 'Space',
		macro: ['space'],
		macroCode: ['KC_SPC'],
	},
	{
		hex: 0x2d,
		code: 'KC_MINUS',
		label: '_\n-',
		macro: ['-'],
		macroCode: ['KC_MINS'],
	},
	{
		hex: 0x2e,
		code: 'KC_EQUAL',
		label: '+\n=',
		macro: ['='],
		macroCode: ['KC_EQL'],
	},
	{
		hex: 0x2f,
		code: 'KC_LBRACKET',
		label: '{\n[',
		macro: ['['],
		macroCode: ['KC_LBRC'],
	},
	{
		hex: 0x30,
		code: 'KC_RBRACKET',
		label: '}\n]',
		macro: [']'],
		macroCode: ['KC_RBRC'],
	},
	{
		hex: 0x31,
		code: 'KC_BSLASH',
		label: '|\n\\',
		macro: ['\\'],
		macroCode: ['KC_BSLS'],
	},
	{
		hex: 0x33,
		code: 'KC_SCOLON',
		label: ':\n;',
		macro: [';'],
		macroCode: ['KC_SCLN'],
	},
	{
		hex: 0x34,
		code: 'KC_QUOTE',
		label: '"\n\'',
		macro: ["'"],
		macroCode: ['KC_QUOT'],
	},
	{
		hex: 0x35,
		code: 'KC_GRAVE',
		label: '~\n`',
		macro: ['`'],
		macroCode: ['KC_GRV', 'KC_ZKHK'],
	},
	{
		hex: 0x36,
		code: 'KC_COMMA',
		label: '<\n,',
		macro: [','],
		macroCode: ['KC_COMM'],
	},
	{ hex: 0x37, code: 'KC_DOT', label: '>\n.', macro: ['.'] },
	{
		hex: 0x38,
		code: 'KC_SLASH',
		label: '?\n/',
		macro: ['/'],
		macroCode: ['KC_SLSH'],
	},
	{
		hex: 0x39,
		code: 'KC_CAPSLOCK',
		label: 'Caps\nLock',
		macro: ['caps lock'],
		macroCode: ['KC_CLCK', 'KC_CAPS'],
	},
	{ hex: 0x3a, code: 'KC_F1', label: 'F1', macro: ['f1'] },
	{ hex: 0x3b, code: 'KC_F2', label: 'F2', macro: ['f2'] },
	{ hex: 0x3c, code: 'KC_F3', label: 'F3', macro: ['f3'] },
	{ hex: 0x3d, code: 'KC_F4', label: 'F4', macro: ['f4'] },
	{ hex: 0x3e, code: 'KC_F5', label: 'F5', macro: ['f5'] },
	{ hex: 0x3f, code: 'KC_F6', label: 'F6', macro: ['f6'] },
	{ hex: 0x40, code: 'KC_F7', label: 'F7', macro: ['f7'] },
	{ hex: 0x41, code: 'KC_F8', label: 'F8', macro: ['f8'] },
	{ hex: 0x42, code: 'KC_F9', label: 'F9', macro: ['f9'] },
	{ hex: 0x43, code: 'KC_F10', label: 'F10', macro: ['f10'] },
	{ hex: 0x44, code: 'KC_F11', label: 'F11', macro: ['f11'] },
	{ hex: 0x45, code: 'KC_F12', label: 'F12', macro: ['f12'] },
	{
		hex: 0x46,
		code: 'KC_PSCREEN',
		label: 'Print\nScreen',
		macroCode: ['KC_PSCR'],
	},
	{
		hex: 0x47,
		code: 'KC_SCROLLLOCK',
		label: 'Scroll\nLock',
		macro: ['scroll lock'],
		macroCode: ['KC_SLCK', 'KC_BRMD'],
	},
	{
		hex: 0x48,
		code: 'KC_PAUSE',
		label: 'Pause',
		macro: ['pause', 'break'],
		macroCode: ['KC_PAUS', 'KC_BRK', 'KC_BRMU'],
	},
	{
		hex: 0x49,
		code: 'KC_INSERT',
		label: 'Insert',
		macro: ['insert'],
		macroCode: ['KC_INS'],
	},
	{ hex: 0x4a, code: 'KC_HOME', label: 'Home', macro: ['home'] },
	{ hex: 0x4b, code: 'KC_PGUP', label: 'Page\nUp', macro: ['page up'] },
	{
		hex: 0x4c,
		code: 'KC_DELETE',
		label: 'Del',
		macro: ['delete'],
		macroCode: ['KC_DEL'],
	},
	{ hex: 0x4d, code: 'KC_END', label: 'End', macro: ['end'] },
	{
		hex: 0x4e,
		code: 'KC_PGDOWN',
		label: 'Page\nDown',
		macro: ['page down'],
		macroCode: ['KC_PGDN'],
	},
	{
		hex: 0x4f,
		code: 'KC_RIGHT',
		label: 'Right',
		macro: ['right'],
		macroCode: ['KC_RGHT'],
	},
	{ hex: 0x50, code: 'KC_LEFT', label: 'Left', macro: ['left'] },
	{ hex: 0x51, code: 'KC_DOWN', label: 'Down', macro: ['down'] },
	{ hex: 0x52, code: 'KC_UP', label: 'Up', macro: ['up'] },
	{
		hex: 0x53,
		code: 'KC_NUMLOCK',
		label: 'Num\nLock',
		macro: ['num lock'],
		macroCode: ['KC_NLCK'],
	},
	{ hex: 0x54, code: 'KC_KP_SLASH', label: '/', macroCode: ['KC_PSLS'] },
	{ hex: 0x55, code: 'KC_KP_ASTERISK', label: '*', macroCode: ['KC_PAST'] },
	{ hex: 0x56, code: 'KC_KP_MINUS', label: '-', macroCode: ['KC_PMNS'] },
	{ hex: 0x57, code: 'KC_KP_PLUS', label: '+', macroCode: ['KC_PPLS'] },
	{
		hex: 0x58,
		code: 'KC_KP_ENTER',
		label: 'Num\nEnter',
		macroCode: ['KC_PENT'],
	},
	{ hex: 0x59, code: 'KC_KP_1', label: '1', macroCode: ['KC_P1'] },
	{ hex: 0x5a, code: 'KC_KP_2', label: '2', macroCode: ['KC_P2'] },
	{ hex: 0x5b, code: 'KC_KP_3', label: '3', macroCode: ['KC_P3'] },
	{ hex: 0x5c, code: 'KC_KP_4', label: '4', macroCode: ['KC_P4'] },
	{ hex: 0x5d, code: 'KC_KP_5', label: '5', macroCode: ['KC_P5'] },
	{ hex: 0x5e, code: 'KC_KP_6', label: '6', macroCode: ['KC_P6'] },
	{ hex: 0x5f, code: 'KC_KP_7', label: '7', macroCode: ['KC_P7'] },
	{ hex: 0x60, code: 'KC_KP_8', label: '8', macroCode: ['KC_P8'] },
	{ hex: 0x61, code: 'KC_KP_9', label: '9', macroCode: ['KC_P9'] },
	{ hex: 0x62, code: 'KC_KP_0', label: '0', macroCode: ['KC_P0'] },
	{ hex: 0x63, code: 'KC_KP_DOT', label: '.', macroCode: ['KC_PDOT'] },
	{
		hex: 0x65,
		code: 'KC_APPLICATION',
		label: 'Menu',
		macro: ['menu', 'left menu', 'right menu'],
		macroCode: ['KC_APP'],
	},
	{ hex: 0x67, code: 'KC_KP_EQUAL', label: '=', macroCode: ['KC_PEQL'] },
	{ hex: 0x85, code: 'KC_KP_COMMA', label: ',', macroCode: ['KC_PCMM'] },
	{
		hex: 0xe0,
		code: 'KC_LCTRL',
		label: 'LCtrl',
		macro: ['left ctrl', 'ctrl'],
		macroCode: ['KC_LCTL'],
	},
	{
		hex: 0xe1,
		code: 'KC_LSHIFT',
		label: 'LShift',
		macro: ['left shift', 'shift'],
		macroCode: ['KC_LSFT'],
	},
	{
		hex: 0xe2,
		code: 'KC_LALT',
		label: 'LAlt',
		macro: ['alt'],
		macroCode: ['KC_LOPT'],
	},
	{
		hex: 0xe3,
		code: 'KC_LGUI',
		label: 'LGui',
		macro: ['left windows', 'windows'],
		macroCode: ['KC_LCMD', 'KC_LWIN'],
	},
	{
		hex: 0xe4,
		code: 'KC_RCTRL',
		label: 'RCtrl',
		macro: ['right ctrl'],
		macroCode: ['KC_RCTL'],
	},
	{
		hex: 0xe5,
		code: 'KC_RSHIFT',
		label: 'RShift',
		macro: ['right shift'],
		macroCode: ['KC_RSFT'],
	},
	{
		hex: 0xe6,
		code: 'KC_RALT',
		label: 'RAlt',
		macroCode: ['KC_ALGR', 'KC_ROPT'],
	},
	{
		hex: 0xe7,
		code: 'KC_RGUI',
		label: 'RGui',
		macro: ['right windows'],
		macroCode: ['KC_RCMD', 'KC_RWIN'],
	},
]

const KEY_CODES_MEDIA = [
	{ hex: 104, code: 'KC_F13', label: 'F13' },
	{ hex: 105, code: 'KC_F14', label: 'F14' },
	{ hex: 106, code: 'KC_F15', label: 'F15' },
	{ hex: 107, code: 'KC_F16', label: 'F16' },
	{ hex: 108, code: 'KC_F17', label: 'F17' },
	{ hex: 109, code: 'KC_F18', label: 'F18' },
	{ hex: 110, code: 'KC_F19', label: 'F19' },
	{ hex: 111, code: 'KC_F20', label: 'F20' },
	{ hex: 112, code: 'KC_F21', label: 'F21' },
	{ hex: 113, code: 'KC_F22', label: 'F22' },
	{ hex: 114, code: 'KC_F23', label: 'F23' },
	{ hex: 115, code: 'KC_F24', label: 'F24' },

	{
		hex: 165,
		code: 'KC_PWR',
		label: 'Power',
		desc: 'System Power Down',
		macroCode: ['KC_SYSTEM_POWER'],
	},
	{
		hex: 166,
		code: 'KC_SLEP',
		label: 'Sleep',
		desc: 'System Sleep',
		macroCode: ['KC_SYSTEM_SLEEP'],
	},
	{
		hex: 167,
		code: 'KC_WAKE',
		label: 'Wake',
		desc: 'System Wake',
		macroCode: ['KC_SYSTEM_WAKE'],
	},
	{
		hex: 116,
		code: 'KC_EXEC',
		label: 'Exec',
		desc: 'Execute',
		macroCode: ['KC_EXECUTE'],
	},
	{ hex: 117, code: 'KC_HELP', label: 'Help' },
	{ hex: 119, code: 'KC_SLCT', label: 'Select', macroCode: ['KC_SELECT'] },
	{ hex: 120, code: 'KC_STOP', label: 'Stop' },
	{ hex: 121, code: 'KC_AGIN', label: 'Again', macroCode: ['KC_AGAIN'] },
	{ hex: 122, code: 'KC_UNDO', label: 'Undo' },
	{ hex: 123, code: 'KC_CUT', label: 'Cut' },
	{ hex: 124, code: 'KC_COPY', label: 'Copy' },
	{ hex: 125, code: 'KC_PSTE', label: 'Paste', macroCode: ['KC_PASTE'] },
	{ hex: 126, code: 'KC_FIND', label: 'Find' },

	{
		hex: 178,
		code: 'KC_CALC',
		label: 'Calc',
		desc: 'Launch Calculator (Windows)',
		macroCode: ['KC_CALCULATOR'],
	},
	{ hex: 177, code: 'KC_MAIL', label: 'Mail', desc: 'Launch Mail (Windows)' },
	{
		hex: 175,
		code: 'KC_MSEL',
		label: 'Media\nPlayer',
		desc: 'Launch Media Player (Windows)',
		macroCode: ['KC_MEDIA_SELECT'],
	},
	{
		hex: 179,
		code: 'KC_MYCM',
		label: 'My\nPC',
		desc: 'Launch My Computer (Windows)',
		macroCode: ['KC_MY_COMPUTER'],
	},
	{
		hex: 180,
		code: 'KC_WSCH',
		label: 'Browser\nSearch',
		desc: 'Browser Search (Windows)',
		macroCode: ['KC_WWW_SEARCH'],
	},
	{
		hex: 181,
		code: 'KC_WHOM',
		label: 'Browser\nHome',
		desc: 'Browser Home (Windows)',
		macroCode: ['KC_WWW_HOME'],
	},
	{
		hex: 182,
		code: 'KC_WBAK',
		label: 'Browser\nBack',
		desc: 'Browser Back (Windows)',
		macroCode: ['KC_WWW_BACK'],
	},
	{
		hex: 183,
		code: 'KC_WFWD',
		label: 'Browser\nForward',
		desc: 'Browser Forward (Windows)',
		macroCode: ['KC_WWW_FORWARD'],
	},
	{
		hex: 184,
		code: 'KC_WSTP',
		label: 'Browser\nStop',
		desc: 'Browser Stop (Windows)',
		macroCode: ['KC_WWW_STOP'],
	},
	{
		hex: 185,
		code: 'KC_WREF',
		label: 'Browser\nRefresh',
		desc: 'Browser Refresh (Windows)',
		macroCode: ['KC_WWW_REFRESH'],
	},
	{
		hex: 186,
		code: 'KC_WFAV',
		label: 'Browser\nFav.',
		desc: 'Browser Favorites (Windows)',
		macroCode: ['KC_WWW_FAVORITES'],
	},
	{
		hex: 189,
		code: 'KC_BRIU',
		label: 'Bright.\nUp',
		desc: 'Increase the brightness of screen (Laptop)',
		macroCode: ['KC_BRIGHTNESS_UP'],
	},
	{
		hex: 190,
		code: 'KC_BRID',
		label: 'Bright.\nDown',
		desc: 'Decrease the brightness of screen (Laptop)',
		macroCode: ['KC_BRIGHTNESS_DOWN'],
	},

	{
		hex: 172,
		code: 'KC_MPRV',
		label: 'Media\nPrev',
		desc: 'Previous Track',
		macroCode: ['KC_MEDIA_PREV_TRACK'],
	},
	{
		hex: 171,
		code: 'KC_MNXT',
		label: 'Media\nNext',
		desc: 'Next Track',
		macroCode: ['KC_MEDIA_NEXT_TRACK'],
	},
	{
		hex: 168,
		code: 'KC_MUTE',
		label: 'Mute',
		desc: 'Mute Audio',
		macroCode: ['KC_AUDIO_MUTE'],
	},
	{
		hex: 170,
		code: 'KC_VOLD',
		label: 'Vol -',
		desc: 'Volume Down',
		macroCode: ['KC_AUDIO_VOL_DOWN'],
	},
	{
		hex: 169,
		code: 'KC_VOLU',
		label: 'Vol +',
		desc: 'Volume Up',
		macroCode: ['KC_AUDIO_VOL_UP'],
	},
	{
		hex: 173,
		code: 'KC_MSTP',
		label: 'Media\nStop',
		macroCode: ['KC_MEDIA_STOP'],
	},
	{
		hex: 174,
		code: 'KC_MPLY',
		label: 'Media\nPlay',
		desc: 'Play/Pause',
		macroCode: ['KC_MEDIA_PLAY_PAUSE'],
	},
	{
		hex: 188,
		code: 'KC_MRWD',
		label: 'Prev\nTrack\n(macOS)',
		desc: 'Previous Track / Rewind (macOS)',
		macroCode: ['KC_MEDIA_REWIND'],
	},
	{
		hex: 187,
		code: 'KC_MFFD',
		label: 'Next\nTrack\n(macOS)',
		desc: 'Next Track / Fast Forward (macOS)',
		macroCode: ['KC_MEDIA_FAST_FORWARD'],
	},
	{
		hex: 176,
		code: 'KC_EJCT',
		label: 'Eject',
		desc: 'Eject (macOS)',
		macroCode: ['KC_MEDIA_EJECT'],
	},

	{
		hex: 240,
		code: 'KC_MS_U',
		label: 'Mouse\nUp',
		desc: 'Mouse Cursor Up',
		macroCode: ['KC_MS_UP'],
	},
	{
		hex: 241,
		code: 'KC_MS_D',
		label: 'Mouse\nDown',
		desc: 'Mouse Cursor Down',
		macroCode: ['KC_MS_DOWN'],
	},
	{
		hex: 242,
		code: 'KC_MS_L',
		label: 'Mouse\nLeft',
		desc: 'Mouse Cursor Left',
		macroCode: ['KC_MS_LEFT'],
	},
	{
		hex: 243,
		code: 'KC_MS_R',
		label: 'Mouse\nRight',
		desc: 'Mouse Cursor Right',
		macroCode: ['KC_MS_RIGHT'],
	},
	{
		hex: 244,
		code: 'KC_BTN1',
		label: 'Mouse\n1',
		desc: 'Mouse Button 1',
		macroCode: ['KC_MS_BTN1'],
	},
	{
		hex: 245,
		code: 'KC_BTN2',
		label: 'Mouse\n2',
		desc: 'Mouse Button 2',
		macroCode: ['KC_MS_BTN2'],
	},
	{
		hex: 246,
		code: 'KC_BTN3',
		label: 'Mouse\n3',
		desc: 'Mouse Button 3',
		macroCode: ['KC_MS_BTN3'],
	},
	{
		hex: 247,
		code: 'KC_BTN4',
		label: 'Mouse\n4',
		desc: 'Mouse Button 4',
		macroCode: ['KC_MS_BTN4'],
	},
	{
		hex: 248,
		code: 'KC_BTN5',
		label: 'Mouse\n5',
		desc: 'Mouse Button 5',
		macroCode: ['KC_MS_BTN5'],
	},
	{
		hex: 249,
		code: 'KC_WH_U',
		label: 'Mouse\nWheel\nUp',
		macroCode: ['KC_MS_WH_UP'],
	},
	{
		hex: 250,
		code: 'KC_WH_D',
		label: 'Mouse\nWheel\nDown',
		macroCode: ['KC_MS_WH_DOWN'],
	},
	{
		hex: 251,
		code: 'KC_WH_L',
		label: 'Mouse\nWheel\nLeft',
		macroCode: ['KC_MS_WH_LEFT'],
	},
	{
		hex: 252,
		code: 'KC_WH_R',
		label: 'Mouse\nWheel\nRight',
		macroCode: ['KC_MS_WH_RIGHT'],
	},
	{
		hex: 253,
		code: 'KC_ACL0',
		label: 'Mouse\nAccel\n0',
		desc: 'Set mouse acceleration to 0',
		macroCode: ['KC_MS_ACCEL0'],
	},
	{
		hex: 254,
		code: 'KC_ACL1',
		label: 'Mouse\nAccel\n1',
		desc: 'Set mouse acceleration to 1',
		macroCode: ['KC_MS_ACCEL1'],
	},
	{
		hex: 255,
		code: 'KC_ACL2',
		label: 'Mouse\nAccel\n2',
		desc: 'Set mouse acceleration to 2',
		macroCode: ['KC_MS_ACCEL2'],
	},

	{
		hex: 130,
		code: 'KC_LCAP',
		label: 'Locking\nCaps',
		desc: 'Locking Caps Lock',
		macroCode: ['KC_LOCKING_CAPS'],
	},
	{
		hex: 131,
		code: 'KC_LNUM',
		label: 'Locking\nNum',
		desc: 'Locking Num Lock',
		macroCode: ['KC_LOCKING_NUM'],
	},
	{
		hex: 132,
		code: 'KC_LSCR',
		label: 'Locking\nScroll',
		desc: 'Locking Scroll Lock',
		macroCode: ['KC_LOCKING_SCROLL'],
	},
]
const KEY_CODES = [...KEY_CODES_BASIC, KEY_CODES_MEDIA]
const BY_HEX = keyBy(KEY_CODES, 'hex')

export const fromHex = (hex: number) => BY_HEX[hex]
export default {
	fromHex,
}
